FROM python:3.11-slim

WORKDIR /tests

COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

COPY tests/ ./tests/
COPY locustfile.py .
COPY app.py .

CMD ["pytest", "tests/", "-v"]
